### PR TITLE
Adding host name support 

### PR DESCRIPTION
**Pull request by Dakotah312**
This adds host and keeps hostaddr so both can be used or neither.

### CODE REVIEW

**Comment by keithf4** [comment]
Would you mind doing a more complete update for this to allow anyone to apply it? Requires making an update file in the same manner as you see here: https://github.com/omniti-labs/pg_jobmon/tree/master/updates. Also requires updating the `.control` file, the META.json file and CHANGELOG. It looks like you started doing some of this but then backed it out?

Since this is changing the API, this would require a bump to the second number of the version: 1.5.0

If not, I'll try and see if I can come back to do a complete update incorporating these changes when I have some time.

**Comment by Dakotah312** [comment]
Yeah, I wasn't sure what all needed changed. I'm still new to postgres extensions and figured if this got merged you would have wanted to do all the version stuff. I can try to get it all ready.

**Comment by Dakotah312** [comment]
Sure I will give it a try. Thanks for the help!

**Review by keithf4 — CHANGES_REQUESTED** [review]

**Comment by Dakotah312** [comment]
Anything else needed for this to get merged?

**Review by keithf4 — APPROVED** [review]

**Comment by keithf4** [comment]
Looks great. Thank you!

**Comment by Dakotah312** [comment]
Thanks you!
How long do you think it will be before 1.5.0 is released?

**Pull request merged**
